/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlydiem_doanck;

import com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class BGH_ThongTinGiangVien extends javax.swing.JFrame {

    /**
     * Creates new form Nhapchinhsuadiem_GV
     */
    public BGH_ThongTinGiangVien() {
        initComponents();
        showKhoa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbthongtin = new javax.swing.JTable();
        CbKhoa = new javax.swing.JComboBox<>();
        btQuaylai = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mgvBox = new javax.swing.JTextField();
        hotenBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        khoaBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lopptBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btTim = new javax.swing.JButton();
        btThem = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btLuu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(99, 172, 229));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN GIẢNG VIÊN");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Tbthongtin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MGV", "HỌ TÊN", "KHOA", "LỚP PHỤ TRÁCH"
            }
        ));
        Tbthongtin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbthongtinMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbthongtin);

        CbKhoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btQuaylai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btQuaylai.setText("Quay lại");
        btQuaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuaylaiActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã GV");

        jLabel3.setText("Họ tên");

        jLabel4.setText("Khoa");

        khoaBox.setToolTipText("");

        jLabel6.setText("Lớp phụ trách");

        lopptBox.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Khoa");

        btTim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btTim.setText("Tìm");
        btTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimActionPerformed(evt);
            }
        });

        btThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btLuu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btLuu.setText("Lưu");
        btLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mgvBox, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(khoaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hotenBox))
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addGap(23, 23, 23)
                .addComponent(lopptBox)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btTim, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(btQuaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CbKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(mgvBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(khoaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lopptBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(hotenBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTim, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btQuaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showKhoa() {
        ArrayList<String> lop = new ArrayList();
        try {
            Connection con = null;
            con = SQLServerConnection.getSQLServerConnection();
            String sql = "SELECT MAKHOA FROM KHOA ";
            SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(sql);

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                lop.add(rs.getString("MAKHOA"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        for (String string : lop) {
            CbKhoa.addItem(string);
        }
    }


    private void btQuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuaylaiActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new BGH_MainFrame().setVisible(true);
            this.setVisible(false);
        });
    }//GEN-LAST:event_btQuaylaiActionPerformed

    private void btTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimActionPerformed
        DefaultTableModel model = (DefaultTableModel) Tbthongtin.getModel();
        model.setRowCount(0);

        String tenkhoa = (String) CbKhoa.getSelectedItem();
        try {
            Connection con = null;
            con = SQLServerConnection.getSQLServerConnection();

            String sql = "SELECT * FROM GIAOVIEN JOIN CTLOPDAY ON GIAOVIEN.MaGV = CTLOPDAY.MaGV WHERE GIAOVIEN.MAKHOA = ? ";
            SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(sql);
            ps.setString(1, tenkhoa);
            ResultSet rs = ps.executeQuery();

            String row[] = new String[4];
            while (rs.next()) {
                row[0] = rs.getString("MAGV");
                row[1] = rs.getString("TENGV");
                row[2] = rs.getString("MAKHOA");
                row[3] = rs.getString("LOPPT");
                model.addRow(row);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btTimActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        DefaultTableModel model = (DefaultTableModel) Tbthongtin.getModel();
        if (mgvBox.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Mã giáo viên không được nhiều hơn 5 ký tự!");
        } else if (khoaBox.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Mã khoa không được nhiều hơn 5 ký tự!");
        } else if (lopptBox.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Mã lớp phụ trách không được nhiều hơn 5 ký tự!");
        } else if (lopptBox.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập mã lớp phụ trách!");
        } else if (khoaBox.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập mã khoa!");
        } else if (mgvBox.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập mã giáo viên!");
        } else if (hotenBox.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập họ tên giáo viên!");

        } else {
            try {
                String row[] = new String[4];
                row[0] = mgvBox.getText();
                row[1] = hotenBox.getText();
                row[2] = khoaBox.getText();
                row[3] = lopptBox.getText();
                model.addRow(row);

                String SQlQuery = "INSERT INTO [GIAOVIEN] VALUES (?,?,?,?,?)";
                Connection con = null;
                con = SQLServerConnection.getSQLServerConnection();
                SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(SQlQuery);
                ps.setString(1, mgvBox.getText());
                ps.setString(2, hotenBox.getText());
                ps.setString(3, lopptBox.getText());
                ps.setString(4, khoaBox.getText());
                ps.setString(5, "Mon Hoc Chua Xac Dinh");

                int n = ps.executeUpdate();

                if (n != 0) {
                    JOptionPane.showMessageDialog(this, "Thêm giáo viên thành công!");

                } else {
                    JOptionPane.showMessageDialog(this, "Thêm giáo viên thất bại!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_btThemActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        DefaultTableModel model = (DefaultTableModel) Tbthongtin.getModel();
        int indexTB = Tbthongtin.getSelectedRow();
        int ret = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa dữ liệu ?", "Xóa dữ liệu", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (ret == JOptionPane.YES_OPTION) {
            if (indexTB < model.getRowCount() && indexTB >= 0) {
                model.removeRow(indexTB);
            }
            String str = "DELETE FROM GIAOVIEN WHERE MAGV = ?";
            try {
                Connection con = null;
                con = SQLServerConnection.getSQLServerConnection();
                SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(str);
                ps.setString(1, mgvBox.getText());
                int n = ps.executeUpdate();

                if (n != 0) {
                    String str1 = "DELETE FROM CTLOPDAY WHERE MAGV = ?";
                    try {

                        SQLServerPreparedStatement ps1 = (SQLServerPreparedStatement) con.prepareStatement(str1);
                        ps1.setString(1, mgvBox.getText());
                        int m = ps1.executeUpdate();

                        if (m != 0) {
                            JOptionPane.showMessageDialog(this, "Xóa thông tin giảng viên thành công!");
                        }

                    } catch (Exception e) {
                        System.err.println(e);

                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi!", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuActionPerformed
        DefaultTableModel model = (DefaultTableModel) Tbthongtin.getModel(); 
        
        int i = Tbthongtin.getSelectedRow();
        String x = model.getValueAt(i, 0).toString();        
        
        if (! mgvBox.getText().equals(x)) {
            JOptionPane.showMessageDialog(this, "Không được thay đổi mã giáo viên !");
        } else if (khoaBox.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Mã khoa không được nhiều hơn 5 ký tự!");
        } else if (lopptBox.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Mã lớp phụ trách không được nhiều hơn 5 ký tự!");
        } else if (lopptBox.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập mã lớp phụ trách!");
        } else if (khoaBox.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập mã khoa!");
        } else if (hotenBox.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập họ tên giáo viên!");
        } else {
            try {
                String strSQL = "UPDATE GIAOVIEN SET TENGV = ?, LOPPT = ?, MAKHOA = ?  WHERE MAGV = ?";
                Connection con = null;
                con = SQLServerConnection.getSQLServerConnection();
                SQLServerPreparedStatement ps = (SQLServerPreparedStatement) con.prepareStatement(strSQL);

                ps.setString(1, hotenBox.getText());
                ps.setString(2, lopptBox.getText());
                ps.setString(3, khoaBox.getText());
                ps.setString(4, mgvBox.getText());
                ps.executeUpdate();

                int indexTB = Tbthongtin.getSelectedRow();
                if (indexTB < model.getRowCount() && indexTB >= 0) {
                    model.setValueAt(hotenBox.getText(), indexTB, 1);
                    model.setValueAt(khoaBox.getText(), indexTB, 2);
                    model.setValueAt(lopptBox.getText(), indexTB, 3);
                }

                int n = ps.executeUpdate();

                if (n != 0) {
                    JOptionPane.showMessageDialog(this, "Lưu thông tin thành công!");
                } else {
                    JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi!", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_btLuuActionPerformed

    private void TbthongtinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbthongtinMouseClicked
        DefaultTableModel model = (DefaultTableModel) Tbthongtin.getModel();
        
        int indexTB = Tbthongtin.getSelectedRow();
        if (indexTB < model.getRowCount() && indexTB >= 0) {
            mgvBox.setText(model.getValueAt(indexTB, 0).toString());
            hotenBox.setText(model.getValueAt(indexTB, 1).toString());
            khoaBox.setText(model.getValueAt(indexTB, 2).toString());
            lopptBox.setText(model.getValueAt(indexTB, 3).toString());
        }
    }//GEN-LAST:event_TbthongtinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BGH_ThongTinGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BGH_ThongTinGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BGH_ThongTinGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BGH_ThongTinGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BGH_ThongTinGiangVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbKhoa;
    private javax.swing.JTable Tbthongtin;
    private javax.swing.JButton btLuu;
    private javax.swing.JButton btQuaylai;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btTim;
    private javax.swing.JButton btXoa;
    private javax.swing.JTextField hotenBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField khoaBox;
    private javax.swing.JTextField lopptBox;
    private javax.swing.JTextField mgvBox;
    // End of variables declaration//GEN-END:variables
}
